// NOTE: after adding/renaming a command below, run `cargo build` and commit the
// regenerated files under src-tauri/gen/ and src-tauri/permissions/autogenerated/.
fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "deliver_notification",
            "report_title",
            "debug_log",
        ]),
    ))
    .expect("failed to run tauri-build");
}
